---
title: "The Promise that R makes: Arguments"
output:
  html_document:
    toc: true
    theme: united
editor_options:
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding-left: 15px;
  padding-right: 15px;
}

.datatables {
    height: 575px !important; 
}
</style>


```{r echo = FALSE, out.width="1000px"}
show_graph("argument_count_by_type")
```

```{r echo = FALSE}
show_table("argument_count_by_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("non_missing_argument_count_by_dot_dot_dot")
```

```{r echo = FALSE}
show_table("non_missing_argument_count_by_dot_dot_dot")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_nature")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_nature")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_sharing")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_sharing")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_expression_type")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_expression_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_value_type")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_force_type")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_force_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_direct_lookup_count")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_direct_lookup_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_direct_and_indirect_lookup_count")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_direct_and_indirect_lookup_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_direct_metaprogram_count")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_direct_metaprogram_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_direct_and_indirect_metaprogram_count")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_direct_and_indirect_metaprogram_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_argument_count_by_dispatch_type")
```

```{r echo = FALSE}
show_table("promise_argument_count_by_dispatch_type")
```

```{r echo = FALSE}
show_table("promise_argument_forced_by_promise_argument")
```

```{r echo = FALSE}
show_table("promise_argument_returning_non_locally")
```

