---
title: "The Promise that R makes: Functions"
output:
  html_document:
    toc: true
    theme: united
editor_options:
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding-left: 15px;
  padding-right: 15px;
}

.datatables {
    height: 575px !important; 
}
</style>


```{r echo = FALSE, out.width="1000px"}
show_graph("function_call_count_by_type")
```

```{r echo = FALSE}
show_table("function_call_count_by_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("function_count_by_type")
```

```{r echo = FALSE}
show_table("function_count_by_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("function_call_count_by_method_type")
```

```{r echo = FALSE}
show_table("function_call_count_by_method_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("function_count_by_method_type")
```

```{r echo = FALSE}
show_table("function_count_by_method_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("closure_count_by_call_count")
```

```{r echo = FALSE}
show_table("closure_count_by_call_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("closure_count_by_formal_parameter_count")
```

```{r echo = FALSE}
show_table("closure_count_by_formal_parameter_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("function_call_count_by_return_value_type")
```

```{r echo = FALSE}
show_table("function_call_count_by_return_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("builtin_count_by_return_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("special_count_by_return_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("closure_count_by_return_value_type")
```

```{r echo = FALSE}
show_table("function_count_by_return_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("closure_count_by_wrapper_and_force_order")
```

```{r echo = FALSE}
show_table("closure_count_by_wrapper_and_force_order")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("function_call_count_by_type_and_jump")
```

```{r echo = FALSE}
show_table("function_call_count_by_type_and_jump")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("function_call_count_by_type_and_jump")
```

```{r echo = FALSE}
show_table("function_call_count_by_type_and_jump")
```

```{r echo = FALSE}
show_table("primitive_function_table")
```

