---
title: "The Promise that R makes: Parameters"
output:
  html_document:
    toc: true
    theme: united
editor_options:
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding-left: 15px;
  padding-right: 15px;
}

.datatables {
    height: 575px !important; 
}
</style>


```{r echo = FALSE, out.width="1000px"}
show_graph("argument_count_by_usage")
```

```{r echo = FALSE}
show_table("argument_count_by_usage")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("formal_parameter_count_by_usage")
```

```{r echo = FALSE}
show_table("formal_parameter_count_by_usage")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("formal_parameter_count_by_usage_class")
```

```{r echo = FALSE}
show_table("formal_parameter_count_by_usage_class")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("closure_count_distribution_by_usage_class")
```

```{r echo = FALSE}
show_table("closure_count_distribution_by_usage_class")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("closure_count_distribution_by_usage_class")
```

```{r echo = FALSE}
show_table("closure_count_distribution_by_usage_class")
```

