---
title: "The Promise that R makes: Promises"
output:
  html_document:
    toc: true
    theme: united
editor_options:
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding-left: 15px;
  padding-right: 15px;
}

.datatables {
    height: 575px !important; 
}
</style>


```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_category")
```

```{r echo = FALSE}
show_table("promise_count_by_category")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_expression_type")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_expression_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("non_argument_promise_count_by_expression_type")
```

```{r echo = FALSE}
show_table("non_argument_promise_count_by_expression_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_value_type")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("non_argument_promise_count_by_value_type")
```

```{r echo = FALSE}
show_table("non_argument_promise_count_by_value_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_creation_scope")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_creation_scope")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("non_argument_promise_count_by_creation_scope")
```

```{r echo = FALSE}
show_table("non_argument_promise_count_by_creation_scope")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_forcing_scope")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_forcing_scope")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("non_argument_promise_count_by_forcing_scope")
```

```{r echo = FALSE}
show_table("non_argument_promise_count_by_forcing_scope")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_dispatch_type")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_dispatch_type")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_call_depth")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_call_depth")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_promise_depth")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_promise_depth")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("argument_promise_count_by_nested_promise_depth")
```

```{r echo = FALSE}
show_table("argument_promise_count_by_nested_promise_depth")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_force_count")
```

```{r echo = FALSE}
show_table("promise_count_by_force_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_metaprogram_count")
```

```{r echo = FALSE}
show_table("promise_count_by_metaprogram_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_value_lookup_count")
```

```{r echo = FALSE}
show_table("promise_count_by_value_lookup_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_value_assign_count")
```

```{r echo = FALSE}
show_table("promise_count_by_value_assign_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_expression_lookup_count")
```

```{r echo = FALSE}
show_table("promise_count_by_expression_lookup_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_expression_assign_count")
```

```{r echo = FALSE}
show_table("promise_count_by_expression_assign_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_environment_lookup_count")
```

```{r echo = FALSE}
show_table("promise_count_by_environment_lookup_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_environment_assign_count")
```

```{r echo = FALSE}
show_table("promise_count_by_environment_assign_count")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_direct_self_scope_mutation")
```

```{r echo = FALSE}
show_table("promise_count_by_direct_self_scope_mutation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_indirect_self_scope_mutation")
```

```{r echo = FALSE}
show_table("promise_count_by_indirect_self_scope_mutation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_direct_lexical_scope_mutation")
```

```{r echo = FALSE}
show_table("promise_count_by_direct_lexical_scope_mutation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_indirect_lexical_scope_mutation")
```

```{r echo = FALSE}
show_table("promise_count_by_indirect_lexical_scope_mutation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_direct_non_lexical_scope_mutation")
```

```{r echo = FALSE}
show_table("promise_count_by_direct_non_lexical_scope_mutation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_indirect_non_lexical_scope_mutation")
```

```{r echo = FALSE}
show_table("promise_count_by_indirect_non_lexical_scope_mutation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_direct_self_scope_observation")
```

```{r echo = FALSE}
show_table("promise_count_by_direct_self_scope_observation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_indirect_self_scope_observation")
```

```{r echo = FALSE}
show_table("promise_count_by_indirect_self_scope_observation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_direct_lexical_scope_observation")
```

```{r echo = FALSE}
show_table("promise_count_by_direct_lexical_scope_observation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_indirect_lexical_scope_observation")
```

```{r echo = FALSE}
show_table("promise_count_by_indirect_lexical_scope_observation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_direct_non_lexical_scope_observation")
```

```{r echo = FALSE}
show_table("promise_count_by_direct_non_lexical_scope_observation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_count_by_indirect_non_lexical_scope_observation")
```

```{r echo = FALSE}
show_table("promise_count_by_indirect_non_lexical_scope_observation")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_use_distribution_by_category")
```

```{r echo = FALSE}
show_table("promise_use_distribution_by_category")
```

```{r echo = FALSE, out.width="1000px"}
show_graph("promise_action_distribution_by_category")
```

```{r echo = FALSE}
show_table("promise_action_distribution_by_category")
```
