``` {r, "basic info", include=FALSE}
library(stringr)

aggregated_functions <- load_local_csv("aggregated_functions.csv", tibble(definition=character()))
metadata <- load_local_csv("metadata.csv", tibble(name=character(), key=character(), value=character()))

basic_info <- 
  load_local_csv("basic_info.csv", 
                 tibble(name="?-?",
                        n.functions=0, n.calls=0, n.promises=0, 
                        n.promise.forces=0, n.promise.lookups=0, 
                        n.alien.promises=0, n.alien.promise.forces=0)) %>%
  group_by(name) %>%
  summarise(
    datasets=paste(name, collapse=", "),
    n.datasets=n(),
    n.functions=sum(as.numeric(n.functions)),
    n.calls=sum(as.numeric(n.calls)),
    n.promises=sum(as.numeric(n.promises)),
    n.promise.forces=sum(as.numeric(n.promise.forces)),
    n.promise.lookups=sum(as.numeric(n.promise.lookups)), 
    n.alien.promises=sum(as.numeric(n.alien.promises)),
    n.alien.promise.forces=sum(as.numeric(n.alien.promise.forces))
  )

 top5_basic_info <- 
   basic_info %>% 
   arrange(desc(n.calls, n.promises, n.promise.accesses, n.functions)) %>% head(5)
 
 aggregate_basic_info <- 
   basic_info %>% summarise(
     name="*",
     datasets=paste(name, collapse=", "),
     n.datasets=n(),
     n.functions=(aggregated_functions %>% count %>% pull(n)),
     n.calls=sum(n.calls),
     n.promises=sum(n.promises),
     n.promise.forces=sum(n.promise.forces),
     n.promise.lookups=sum(n.promise.lookups), 
     n.alien.promises=sum(n.alien.promises),
     n.alien.promise.forces=sum(n.alien.promise.forces)
   )
 
 missing_basic_info <- 
   basic_info %>% summarise(
     name="...",
     datasets="...",
     n.datasets="...",
     n.functions="...",
     n.calls="...",
     n.promises="...",
     n.promise.forces="...",
     n.promise.lookups="...", 
     n.alien.promises="...",
     n.alien.promise.forces="..."
   )

 n.packages <- basic_info %>% count %>% pull(n)
 
 # some graphical stuff
 package_figure_width <- 10
 package_figure_columns <- min(7, ceiling(sqrt(n.packages)))
 package_figure_rows <- ceiling(n.packages/package_figure_columns)
 package_figure_height <- ceiling(10/7 * package_figure_rows)
```
# Dataset

```{r, "dataset", echo=FALSE, comment="", row.names=FALSE}
#select(name) %>% distinct %>% pull(name) %>% as.character %>% print(row.names=FALSE)
metadata %>% 
filter(!grepl("^PROBE", key)) %>% filter(!grepl("^EXPRESSION", key)) %>% filter(!grepl("^DYNTRACE", key)) %>% 
group_by(key, value) %>% summarize(occurances=n()) %>% kable(col.names=c("key", "value", "occurances"), align="lrr")

basic_info %>%
   mutate(package=str_split_fixed(name, "-", n=2)[,1], vignette=str_split_fixed(name, "-", n=2)[,2]) %>% 
   group_by(package) %>% summarize(vignettes=n()) %>% 
   ungroup() %>% summarize(packages=n(), vignettes=sum(vignettes)) %>% 
   kable(col.names=c("packages", "vignettes"), align="lr")
```

<!--r path -->
# Overview

``` {r, "overview", echo=FALSE, warning=FALSE}
union(top5_basic_info, aggregate_basic_info) %>% 
  mutate(
    n.functions=pp_trunc(n.functions), 
    n.calls=pp_trunc(n.calls), 
    n.promises=pp_trunc(n.promises), 
    n.promise.accesses=pp_trunc(n.promise.forces + n.promise.lookups),
    n.promise.forces=pp_trunc(n.promise.forces),
    n.promise.lookups=pp_trunc(n.promise.lookups)
  ) %>% 
  select(name, n.functions, n.calls, n.promises, 
         n.promise.accesses, n.promise.forces, 
         n.promise.lookups) %>%  
  kable(col.names=c("package", "functions", "calls", "promises",
                    "promise accesses", "promise forces",
                    "promise lookups"), align="lrrrrrr")
```

<div style="font-size: 50%; padding-top: 2em">
**promise force** means the promise is accessed and the code of the promise is executed  
**promise lookup** mean the promise is accessed and the code of the promise is not executed
</div>

<!--div style="font-size: 50%;">
(showing top 5)
</div-->

<!--Alien promises are promises which were created before we began tracing. We don't have all the information regarding them, so we generally ignore them, including in the data below. They also are a subject of a lot of lookups in functions `from base::*`, which we don't record to save disk space.-->

