# Promise accesses

```{r, "promise accesses", include=FALSE}
forces <- 
	  load_local_csv("fuzzy_forces.csv") %>% 
	  group_by(classification) %>% 
	  summarise(number=sum(as.numeric(number), na.rm=TRUE)) %>% 
	  mutate(percent=100*number/sum(number))
	```

``` {r, "promise accesses kable", echo=FALSE}
forces %>% prettify %>% kable(col.names=c("classification","number","percentage"), align="lrr")
```

<!--``` {r evaluations-forces-graph, echo=FALSE, comment="", fig.width=10, fig.height=5}
ggplot(forces, aes(x="", y=percent, fill=classification)) + 
  geom_bar(width=1, stat="identity") + 
    #geom_text(aes(y=cumsum(percent)-percent/2, label=classification)) +
      coord_polar("y", start=0) +
        theme(legend.position="right", axis.title.y=element_blank())
	```-->

<div style="font-size: 50%; padding-top: 2em">
**promise force** means the promise is accessed and the code of the promise is executed  
**promise lookup** mean the promise is accessed and the code of the promise is not executed
</div>
